server:
  port: 9527

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 49c0c7f8-ee2c-4186-8634-7160f6b3baaf


    gateway:
      routes:
        - id: login
          uri: http://localhost:20000
          predicates:
            - Path=/api/login/**

#        config:
#          namespace: 49c0c7f8-ee2c-4186-8634-7160f6b3baaf
#          group: PROVIDER_GROUP
#          server-addr: 127.0.0.1:8848
#          file-extension: yaml