server:
  port: 20000

spring:
  application:
    name: ssc-auth-center

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 49c0c7f8-ee2c-4186-8634-7160f6b3baaf

        config:
          namespace: 49c0c7f8-ee2c-4186-8634-7160f6b3baaf
          group: PROVIDER_GROUP
          server-addr: 127.0.0.1:8848
          file-extension: yaml

    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  security:
    user:
      name: vurtne
      password: 123
      roles: admin



# ${prefix}-${spring:profiles:active}:${file-extension}:

management:
  endpoints:
    web:
      exposure:
        include: '*'





